require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CarDriversController do

  # This should return the minimal set of attributes required to create a valid
  # CarDriver. As you add validations to CarDriver, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CarDriversController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all car_drivers as @car_drivers" do
      car_driver = CarDriver.create! valid_attributes
      get :index, {}, valid_session
      assigns(:car_drivers).should eq([car_driver])
    end
  end

  describe "GET show" do
    it "assigns the requested car_driver as @car_driver" do
      car_driver = CarDriver.create! valid_attributes
      get :show, {:id => car_driver.to_param}, valid_session
      assigns(:car_driver).should eq(car_driver)
    end
  end

  describe "GET new" do
    it "assigns a new car_driver as @car_driver" do
      get :new, {}, valid_session
      assigns(:car_driver).should be_a_new(CarDriver)
    end
  end

  describe "GET edit" do
    it "assigns the requested car_driver as @car_driver" do
      car_driver = CarDriver.create! valid_attributes
      get :edit, {:id => car_driver.to_param}, valid_session
      assigns(:car_driver).should eq(car_driver)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CarDriver" do
        expect {
          post :create, {:car_driver => valid_attributes}, valid_session
        }.to change(CarDriver, :count).by(1)
      end

      it "assigns a newly created car_driver as @car_driver" do
        post :create, {:car_driver => valid_attributes}, valid_session
        assigns(:car_driver).should be_a(CarDriver)
        assigns(:car_driver).should be_persisted
      end

      it "redirects to the created car_driver" do
        post :create, {:car_driver => valid_attributes}, valid_session
        response.should redirect_to(CarDriver.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved car_driver as @car_driver" do
        # Trigger the behavior that occurs when invalid params are submitted
        CarDriver.any_instance.stub(:save).and_return(false)
        post :create, {:car_driver => {}}, valid_session
        assigns(:car_driver).should be_a_new(CarDriver)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CarDriver.any_instance.stub(:save).and_return(false)
        post :create, {:car_driver => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested car_driver" do
        car_driver = CarDriver.create! valid_attributes
        # Assuming there are no other car_drivers in the database, this
        # specifies that the CarDriver created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CarDriver.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => car_driver.to_param, :car_driver => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested car_driver as @car_driver" do
        car_driver = CarDriver.create! valid_attributes
        put :update, {:id => car_driver.to_param, :car_driver => valid_attributes}, valid_session
        assigns(:car_driver).should eq(car_driver)
      end

      it "redirects to the car_driver" do
        car_driver = CarDriver.create! valid_attributes
        put :update, {:id => car_driver.to_param, :car_driver => valid_attributes}, valid_session
        response.should redirect_to(car_driver)
      end
    end

    describe "with invalid params" do
      it "assigns the car_driver as @car_driver" do
        car_driver = CarDriver.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CarDriver.any_instance.stub(:save).and_return(false)
        put :update, {:id => car_driver.to_param, :car_driver => {}}, valid_session
        assigns(:car_driver).should eq(car_driver)
      end

      it "re-renders the 'edit' template" do
        car_driver = CarDriver.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CarDriver.any_instance.stub(:save).and_return(false)
        put :update, {:id => car_driver.to_param, :car_driver => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested car_driver" do
      car_driver = CarDriver.create! valid_attributes
      expect {
        delete :destroy, {:id => car_driver.to_param}, valid_session
      }.to change(CarDriver, :count).by(-1)
    end

    it "redirects to the car_drivers list" do
      car_driver = CarDriver.create! valid_attributes
      delete :destroy, {:id => car_driver.to_param}, valid_session
      response.should redirect_to(car_drivers_url)
    end
  end

end
